server:
  port: 8080

spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/escape-master_data?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.team6.escapemaster_server.entity

#showSql
logging:
  level:
    com:
      team6:
        escapemaster_server:
          mapper : debug


